[Add] 記者毎の投稿記事を見れるページを追加
vim-jp/ekiden pull request #101
Opened 2023-05-29 10:52 UTC by staticWagomU

`/ekiden/writer/author/`にauthor毎の投稿記事一覧を見れるページを追加しました

![image](https://github.com/vim-jp/ekiden/assets/34824645/75f63848-6c8e-4026-ac79-44fc9e8a2a6c)

2023-05-29 13:19 UTC, monaqa commented
方向性としては良さそうです。
今後「区」の概念（3ヶ月？）とかが決まってきたら、年のかわりに区で切って表示するようにしてもいいかもですね。
（今後の方針にもよるのでこの PR で対応しなくて良いと思います）

以下要望・質問

* 冒頭の執筆者名のところは、もう少し見出し感がほしいです。 h1 のデフォルトレイアウトでもいいぐらいなんですが。
* トップページやアーカイブページから飛べたほうが良さそうですが、リンク付与はこの PR では対応しない感じですか？（別 PR でも良いと思います）

2023-05-29 14:56 UTC, monaqa reviewed
追加で気づいた点コメントしました。

2023-05-29 14:56 UTC, monaqa commented on src/pages/writer/[writer].astro
> +<Base title="Vim 駅伝 - 記者一覧" slug="/writer/">
「記者」はちょっと違和感ありますね。「執筆者」「ライター」とかがいいかもしれません。
runner なら「走者」とする手もありますね。

2023-05-29 14:56 UTC, monaqa commented on src/pages/writer/[writer].astro
> +  .filter((article) => article.author === writer)
今の実装だとパスの構成要素に JSON の "author" フィールドを使うようになっていますが、 "author" フィールドは使える文字種の制約がほとんどないはずで、 URL のパスとするのに少し不安があります。たとえばスラッシュが含まれている場合トラブルが起きそうな気がします。
author フィールドのかわりに、githubUser フィールドを用いるようにしてみてはどうでしょうか。記事の登録には GitHub のアカウントが必須なので `githubUser` は non null ですし、アカウント名であれば alphanumeric or hyphen の厳しい制約があるので、URL のパスとして申し分ありません。

2023-07-13 00:34 UTC, ArcCosine requested changes
```<Base title={`Vim 駅伝 - ${writer}の記事一覧`} slug="/writer/">```

この部分で、lintエラーが出ています。
writerがundefinedになる可能性があるので、

```<Base title={`Vim 駅伝 - ${writer || ""}の記事一覧`} slug="/writer/">```

のようにundefined対策を入れていただければと思います。

2023-07-13 13:00 UTC, ArcCosine approved these changes

2023-07-13 13:01 UTC, merged

2023-07-15 10:20 UTC, thinca reviewed
すでにマージ済みですが、今後も見据えてコメントしました。
一覧ページへの導線も考える必要がありますね。

2023-07-15 10:20 UTC, thinca commented on src/pages/runner/[runner].astro
個人的には `runners` が好みでしたが…この辺りの議論ってしましたっけ。

2023-07-15 10:20 UTC, thinca commented on src/pages/runner/[runner].astro
> +  <h1>{runner}</h1>
h1 のスタイルがないので見た目が寂しいですね。追加で対応できるとよさそう。
![image](https://github.com/vim-jp/ekiden/assets/20474/40baf90b-54fb-4ae4-9903-77dc2c635345)