Implement `getArticles` to parse content.json
vim-jp/ekiden pull request #319
Opened 2024-03-02 17:16 UTC by ryoppippi

`getArticles`関数を作ってcontent.jsonを読み込む処理を共通化する

2024-03-02 17:26 UTC, ryoppippi commented
これがマージされたら、componentの共通化をやっていく予定

2024-03-03 05:30 UTC, monaqa requested changes
とりあえず修正お願いしたいところがあったのでコメントします

2024-03-03 05:30 UTC, monaqa commented on src/lib/article.ts
> +      /** 記事の日付を降順に並び替え */
これ「昇順」じゃないですか？

2024-03-03 05:30 UTC, monaqa commented on src/pages/archives/[section].astro
> +                  <div class="text-lg font-bold">#{index + 1}</div>
[must] この変更によって、記事一覧表示時の連番がリセットされちゃってますね。ここは season 毎のページでも、全記事を通してのインデックス番号が表示されるように修正してほしいです。

2024-03-03 05:32 UTC, monaqa commented on src/pages/archives/[section].astro
> +                  <div class="text-lg font-bold">#{index + 1}</div>
今 preview してみるとこんな感じで表示されますが、`#1` ではなく `#158` が表示されてほしい、って感じです
![image](https://github.com/vim-jp/ekiden/assets/48883418/8d322778-85bc-44f7-8c24-1bf9e3397b35)

2024-03-03 05:36 UTC, ryoppippi commented
ありがとうございます！対応します

2024-03-03 05:37 UTC, ryoppippi commented on src/lib/article.ts
> +      /** 記事の日付を降順に並び替え */
昇順です！

2024-03-03 05:44 UTC, monaqa requested changes
全体見ました。あと2点追加でご対応お願いします。

index については、 `getArticles` の戻り値に通し番号としての index を追加してしまうのが良さそうですね。

2024-03-03 05:44 UTC, monaqa commented on src/pages/index.astro
> +const newestArticle = articles.pop();
ここの変更によって後々の `<Articles articles={articles} />` にわたす `articles` の値が変わってしまい、「公開された最新の記事」や「登録済みだが未公開の記事」が articles に渡されなくなってしまってますね。

![image](https://github.com/vim-jp/ekiden/assets/48883418/87a97311-db59-4c8a-aead-cabebc243d5c)

二度呼び出すことにはなってしまいますが、以下のように書くのはどうでしょう。

```
const articles = getArticles();
const newestArticle = getArticles({ isPublished: true }).pop();
```

2024-03-03 05:44 UTC, monaqa commented on src/pages/ranking/[section].astro
> +});
（どちらでも構いませんが）折角なのでオプションを使うとよさそうですね！

```suggestion
const articles = getArticles({isPublished: true}).filter((article) => {
  const articleSection = dateToSection(dayjs(article.date));
  return (
    articleSection.fiscalYear == section.fiscalYear &&
    articleSection.season == section.season
  );
});
```

2024-03-03 05:44 UTC, monaqa commented on src/pages/runners/[runner].astro
> +                    <div class="text-lg font-bold">#{index + 1}</div>
こちらの表示も、全体を通しての index が表示されるように修正お願いします。

2024-03-03 05:47 UTC, ryoppippi commented on src/pages/index.astro
> +const newestArticle = articles.pop();
了解です！よく見えてませんでした
確かに、元の実装通り別々にしちゃうのはアリですね

2024-03-03 05:54 UTC, ryoppippi commented on src/pages/ranking/[section].astro
> +});
確かにそうですね！そうします！

2024-03-03 06:17 UTC, ryoppippi commented on src/pages/archives/[section].astro
> +                  <div class="text-lg font-bold">#{index + 1}</div>
了解です！修正ずみ（のはずです

2024-03-03 06:20 UTC, ryoppippi commented
@monaqa 
修正しました！お願いします

2024-03-03 06:32 UTC, monaqa requested changes
1箇所バグが残ってたので修正お願いします 🙏🏼

2024-03-03 06:32 UTC, monaqa commented on src/pages/archives/index.astro
> +                  <div class="text-lg font-bold">#{index + 1}</div>
どちらでも問題無さそうですが、特に理由がなければこちらも `[section].astro` 側に合わせて `article.originalIndex + 1` にしてよいかなと思いました

2024-03-03 06:32 UTC, monaqa commented on src/pages/runners/[runner].astro
> +              runnersArticles.at(Math.max(article.originalIndex - 1, 0))?.year
ここのロジックが変わったために、最初以外全ての記事で年度表示が出るようになってしまってますね。修正お願いします。

![image](https://github.com/vim-jp/ekiden/assets/48883418/4a50ae41-1ea7-42fd-9cc1-74464b2be495)

ちょっと面倒ですが、元のロジックのまま実装するなら、ここは `originalIndex` とは別の index を置くしかない気がしますね。

2024-03-03 06:32 UTC, monaqa commented on src/lib/article.ts
> +        originalIndex: index,
`originalIndex` は主に UI 上で表示する通し番号のため使われるので、最初から `index + 1` で定義しておくのもアリかなと思いました。
ただ 0 オリジンで統一したほうが分かりやすいという気持ちも分かるので、どちらでも良いと思います。

2024-03-03 06:35 UTC, ryoppippi commented on src/pages/archives/index.astro
> +                  <div class="text-lg font-bold">#{index + 1}</div>
そうですねそうしましょう
というかcommentつけておきます

2024-03-03 06:35 UTC, ryoppippi commented on src/lib/article.ts
> +        originalIndex: index,
コメント書きますね！

2024-03-03 16:16 UTC, ryoppippi commented on src/pages/runners/[runner].astro
> +              runnersArticles.at(Math.max(article.originalIndex - 1, 0))?.year
修正済みです！
<img width="526" alt="Screenshot 2024-03-04 at 01 15 59" src="https://github.com/vim-jp/ekiden/assets/1560508/919d19a3-0802-4390-9172-bd11a62fbcab">

2024-03-03 16:17 UTC, ryoppippi commented
@monaqa 
レビューありがとうございます！
修正しました！

2024-03-03 16:18 UTC, ryoppippi commented on src/pages/archives/[section].astro
> +                  <div class="text-lg font-bold">#{index + 1}</div>
<img width="739" alt="Screenshot 2024-03-04 at 01 18 08" src="https://github.com/vim-jp/ekiden/assets/1560508/83d7e666-82b8-4a01-bbb1-bee9c283d1b4">


修正済みです！

2024-03-03 16:23 UTC, ryoppippi commented
@monaqa
レビューありがとうございます！
修正しました！

2024-03-04 08:10 UTC, monaqa commented
（修正差分が分からなくなるので、今後はできれば rebase は approve 後に行ってほしいです…）

2024-03-04 08:30 UTC, ryoppippi commented
了解です！
変更する→approveしてもらう→rebase→再レビュー
って流れでしょうか?

2024-03-04 08:36 UTC, monaqa commented
はい、レビュー中は変更差分を積んでもらったほうがレビュアーはレビューしやすいですね。
無駄なコミットが気になる場合は approve 後に手動で rebase するか、squash-merge とか rebase-merge してもらってもいいかもです（私はあんまりやったことないですが）

2024-03-04 08:47 UTC, ryoppippi commented
なるほど了解です！ありがとうございます

2024-03-04 08:47 UTC, monaqa approved these changes
本 PR についてはひとまず問題無さそうです！
ありがとうございます。

2024-03-04 08:48 UTC, ryoppippi commented
ありがとうございます！

2024-03-04 08:49 UTC, monaqa commented
ということでマージします。
かなりソースコードの見栄えが良くなった気がします。ありがとうございました 🙏🏼

2024-03-04 08:49 UTC, merged