create `ArticleInArchive` component
vim-jp/ekiden pull request #337
Opened 2024-03-08 06:28 UTC by ryoppippi

Archiveやrunnerのページで表示されている記事のcomponentをまとめる

2024-03-08 06:34 UTC, ryoppippi commented on src/components/ArticleInArchive.astro
> +          <h3 class="text-md mb-1 font-bold md:text-lg">
元のページたちには
aタグの中にaタグ
の実装がされていたのだが、あんまよろしくないのでとりあえずrunner部分のaタグは抜いています
あとでどうするか検討しましょう

2024-03-08 06:35 UTC, ryoppippi commented on src/pages/archives/[section].astro
> -                </p>
元のページたちには
aタグの中にaタグ
の実装がされていたのだが、あんまよろしくないのでとりあえずrunner部分のaタグは抜いています
あとでどうするか検討しましょう

2024-03-10 04:07 UTC, monaqa requested changes
一点コメントしました。

2024-03-10 04:07 UTC, monaqa commented on src/pages/archives/[section].astro
> -                </p>
> aタグの中にaタグ

これ私も気になってはいたんですが、ここ抜いちゃうと `[runner].astro` への導線がなくなりますよね。
アクセスできなくなるよりは「あんまよろしくない」状態の維持のほうがマシな気はするので、復活させてもらえると助かります。

2024-03-10 06:56 UTC, ryoppippi commented on src/pages/archives/[section].astro
> -                </p>
修正しました！

2024-03-10 10:28 UTC, monaqa approved these changes
ご対応ありがとうございます！
コードの重複が無くなり、改善されたと思います。

a タグ in a タグ の件については issue 化しました → #338

2024-03-10 14:04 UTC, merged