Timeline layout.
vim-jp/ekiden pull request #52
Opened 2023-03-11 11:41 UTC by tani

Fixes #19 . 

Vim 駅伝のページからカレンダーを消すという提案が #19　にてなされており、
このプルリクエストでは、その提案に沿ってデザインしたものになります。

![image](https://user-images.githubusercontent.com/5019902/224482084-03b545aa-d3d0-4f9b-b2c6-be0d4b1fb6b7.png)

以下で動かすことができます。ぜひ、挙動等でコメントを頂戴したいです。

https://stackblitz.com/github/tani/ekiden/tree/timeline

なお、次のことは行っていないので、上手な方にお任せしたいです。

- Tailwind 対応

2023-03-11 11:59 UTC, kyoh86 commented
飽くまで見た目の感想だけになりますけど、

- 見る側からすると『月日』はどうでもいい情報なので、最低限に落ちてる感じが良い
    - 情報確度としての年月日に意味はあるけど、リンク集の担う役割ではない
- タイトル文字が弱めなので、背景にも文字がある中でこれが重なるとゴチャついて読みにくいかも
    - ![image](https://user-images.githubusercontent.com/5582459/224483011-5456ec37-5a6c-4182-8e31-4e0399f7d878.png)
    - 色を落とすか、背景には文字（vim駅伝）ナシにするか、でよさそう

2023-03-11 12:03 UTC, tani commented
たすきを消してみました。

2023-03-11 12:14 UTC, monaqa commented
駅伝感が強くなって良くなったと思いますー。
いくつかコメントです。

* 数字だけだと何を表しているかわかりづらくなりそうなので、「3月」とか「1日」とかあっても良いと思います。
    * あと、3月が2月になってます。（これ本当に紛らわしいと思うんですが、`.month()` は 0 始まりなんですよね）
* すべての記事を載せると、トップページにしては長い & 参加登録までの必要なスクロール数が多くなってしまうので、今月だけとか、ある程度絞ったほうが良さそうです。
* モバイル表示で長いタイトルにする（4行以上）と次の記事とテキストが被ってしまうのですが、こちら何らかの方法で回避できるでしょうか？1記事あたりの縦の長さを可変にするのがベストだと思います。

2023-03-11 12:29 UTC, kawarimidoll requested changes

2023-03-11 12:29 UTC, kawarimidoll commented on src/components/Article.astro
> +  opened?: bool;
ここは`boolean`かと思います
```suggestion
  firstDay?: boolean;
  opened?: boolean;
```

2023-03-11 12:34 UTC, tani commented
- 月日の追加を行いました。
- 掲載区間の調整はTODO
- 長いタイトルのためのストレッチもTODO (斜め線計算が、ボックスの高さに依存しているので、ボックスの高さが静的に決まる必要があリます。ただし、うまく書けば、何とかなりそう。)

2023-03-11 13:02 UTC, kawarimidoll commented on src/components/Articles.astro
> +    }
imo: letしてundefinedのときに再代入するより、[Null 合体演算子](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing)でフォールバックするのが良い気がします

```js
// findおよび募集中articleの中身は省略
const article = Astro.props.articles.find( ... ) ?? { ... };
```

2023-03-11 13:09 UTC, tani commented on src/components/Articles.astro
> +    }
ありがとうございます。修正しました!

2023-03-13 19:15 UTC, ArcCosine commented
https://user-images.githubusercontent.com/40669/224805393-5065a92f-ea05-4d76-9c2b-365a11448417.mp4

こちら、Windows上での動きなのですが、hover時、斜め線が震える挙動をしていて違和感を感じました。
斜め線をafter要素で追加していますが、ダミーのHTMLを追加して影響を受けないようにした方が良いかもしれません。

2023-03-19 09:37 UTC, tani commented
@monaqa 
- 表示区間をレンダリング時の１ヶ月前から１ヶ月後まで表示するようにしました。
- タイトルを表示する部分の要素の高さは min-heightとして設定したため、それよりも高くなるときは自動でストレッチすると思われます

@ArcCosine 
斜線の計算方法を変えました。多分震えなくなったと思います。確認よろしくお願いします

2023-03-21 02:01 UTC, ArcCosine approved these changes

2023-03-21 10:42 UTC, monaqa commented
ありがとうございます。

* 手元で試してみたところ、たしかにストレッチはしますが、線は途切れてしまうようですね。

![スクリーンショット 2023-03-21 19 39 30](https://user-images.githubusercontent.com/48883418/226582471-147258be-138a-42fa-8bdb-c3bf8e6c3e61.png)

とはいえこれぐらいなら別 PR での修正でも問題ないと思います。
イベント概要が埋まればマージでよいかなと。

2023-03-21 14:15 UTC, tani commented
線が途切れる問題を修正しました。コメントありがとうございました！

2023-03-24 13:32 UTC, ArcCosine approved these changes
LGTM

2023-03-26 13:34 UTC, monaqa commented
@tani 以下の文言を冒頭のセクション内に入れていただけますか？
（section の高さが現在 150px 固定なので、その指定は消していただければ）

```html
          <h2>Vim 駅伝とは</h2>
          <p>
            Vimmerを中心に技術的なコンテンツを持ち寄り、リレー形式で記事をリンクする営みです。
            GitHub のアカウントさえあれば誰でも投稿できます。
            小さなノウハウ、ちょっとした気づき、作ったプラグイン、開発の苦労話など、
            Vim またはテクノロジーに関連していればどんな些細な内容でもかまいません。
            皆さんの手で、Vim 駅伝を盛り上げていきましょう！
          </p>
          <h2>注意事項</h2>
          <ul>
            <li>
              個人攻撃や差別的な内容を含む記事、公序良俗に反する不適切な記事の投稿を禁止します。
              明らかに不適切と判断された記事については、GitHub 経由での通告のもと本ページからリンクを削除する場合があります。
            </li>
          </ul>
```

2023-03-30 00:38 UTC, tani commented
@monaqa 反映いたしました。よろしくお願いします！

2023-03-30 01:21 UTC, monaqa requested changes
すいません、一点だけ修正お願いします。

2023-03-30 01:21 UTC, monaqa commented on src/pages/index.astro
> +    height: 150px;
すいません、伝え忘れてましたがこれ消す必要がありますね（おそらくもともと暫定的に付けていた？）。

2023-03-30 02:47 UTC, tani commented on src/pages/index.astro
> +    height: 150px;
ご指摘ありがとうございます。高さ調整のスペースを削除しました。

2023-03-30 13:20 UTC, monaqa approved these changes
対応ありがとうございました！

2023-03-30 13:20 UTC, merged