Entry from issue
vim-jp/ekiden pull request #7
Opened 2023-02-23 18:30 UTC by thinca

テンプレートから Issue を作成すると、`content.json` を更新します。

以下の fork リポジトリで動作確認ができます。このリポジトリはこの PR がマージされたら一旦削除する予定なので、自由に Issue を立てまくって動作確認してもらって大丈夫です。何かおかしな動作を見つけたら教えてください。

https://github.com/thinca/ekiden/issues/new?assignees=&labels=article&template=article.yml

- テンプレートから、参加日(`YYYY-mm-dd`)をタイトルに入れて Issue を立てると workflow が実行されて、`content.json` にエントリーを追加します。
  - deploy key 経由で `main` ブランチに push されます。この push によりサイトの deploy も自動で行われます。
  - deploy key のリポジトリへの登録は先に済ませました。
- Issue の本文を編集すると、変更内容が同様に push されます。
- 入力内容に不備があった場合、その内容をコメントして Issue をクローズします。内容を修正して再オープンすると再処理されます。
- Issue を閉じると、エントリーが解除されます。

## 将来の TODO (別 PR)

- 使い方の詳細な説明ページを用意し、テンプレートからリンクを貼る
- 当日になったら自動で close する workflow を用意する

2023-02-23 23:12 UTC, monaqa requested changes
まだちゃんと確認できてませんが、以下エラーの原因っぽいところだけコメントしておきます！

https://github.com/thinca/ekiden/issues/10

2023-02-23 23:12 UTC, monaqa commented on scripts/update-article.ts
> +        }
content が empty でないときの分岐で `author = content` 的なものを入れないと、執筆者名が空でないとき `author` が null のままになってしまうような気がします。

2023-02-24 06:46 UTC, skanehira commented on scripts/update-article.ts
> +  return JSON.parse(Deno.readTextFileSync(CONTENT_JSON_PATH));
せっかくだからzodを使ってバリデーション噛ますとよさそう？
https://deno.land/x/zod@v3.20.5

2023-02-25 03:57 UTC, monaqa commented
> 入れるなら「エントリーしました」(初回のみ)「キャンセルしました」(クローズしてキャンセルした時) とかの方がいいかも。

初回・キャンセル時でコメント変えるのは良いと思います！
どんな種類の操作が行われたのかぱっと把握できるのは便利な気がするので、コメント自体はあって良さそうです。

2023-02-25 04:02 UTC, monaqa commented
これはどちらかというと仕様の相談ですが、登録した日付よりも前の日を指定してエントリーするのってアリにします？ナシにします？

* `2022-03-01` みたいに間違えて指定してしまうミスは防ぎたい
* アドベントカレンダーのように空席が生じてしまったとき、それを後日埋められるようにはしてもいいかも

2023-02-25 11:52 UTC, monaqa commented
お、良さそうですね。それでいきましょう

2023-02-26 14:23 UTC, monaqa commented
> 公開日当日に、自動で close するワークフローを走らせる予定だけど、走る前に手動で閉じられてしまった場合にキャンセル扱いになってしまう。やめてくれと言う話ではあるが、できれば回避したい。

ちなみに公開日当日を過ぎてしまってからキャンセルする術ってあるんでしたっけ？

2023-02-26 15:02 UTC, monaqa approved these changes
一旦マージして良さそうな気がします

2023-02-26 15:10 UTC, kyoh86 commented on .github/workflows/update-article.yml
> +               2>> "${GITHUB_OUTPUT}"
理想的には `update-article.ts` の中で何やってるかのログは別途出しておくと良いとは思いますけど、まぁいつでも。

2023-02-26 15:14 UTC, kyoh86 commented on .github/workflows/update-article.yml
> +               --githubUser '${{ github.event.issue.user.login }}' \
:memo: github.event.issue.user はissueを作った人であって、 **編集した人ではない** ので問題ない。
編集した人は sender.login
https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads

2023-02-26 15:16 UTC, kyoh86 commented
URLを空でIssueを作る→編集してURLを設定する（ `http://example.com` と入力した）と、Articleが消されるケースがあるっぽい。
https://github.com/thinca/ekiden/actions/runs/4275563192/jobs/7443009348
`delete` 渡ってるわけではないので、 update-article.ts の問題？

コントロール元のIssue: https://github.com/thinca/ekiden/issues/15

2023-02-26 17:24 UTC, merged